name: GitHub Actions Demo
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew clean build
  lint-markdown:
    name: Lint all markdowns in project
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Lint markdowns
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: '**/*.md'
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew clean assemble spotbugsMain
      - uses: jwgmeligmeyling/spotbugs-github-action@master
        with:
          path: '**/spotbugs.xml'
  testCoverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew build jacocoTestReport
      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60
      - name: Archive code coverage results
        uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: build/reports/jacoco/**
      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: build/reports/jacoco/test/jacocoTestReport.csv
          generate-coverage-badge: true
          badges-directory: .github/badges
      - name: Commit the badge (if it changed)
        run: |
          git config --global user.name 'secvisogram tech user'
          git config --global user.email 'rainer-exxcellent@users.noreply.github.com'
          if [[ `git status --porcelain` ]]; then
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
  generateSwaggerDocumentation:
    needs: testCoverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run Coverage
        run: |
          chmod +x gradlew
          ./gradlew clean build
      - name: Commit the documentation
        run: |
          git config --global user.name 'secvisogram tech user'
          git config --global user.email 'rainer-exxcellent@users.noreply.github.com'
          if [[ `git status --porcelain` ]]; then
            git add documents/generated/index.adoc -A
            git add documents/generated/index.html -A
            git commit -m "Autogenerated Swagger documentation"
            git push
          fi