name: GitHub Actions Demo
on: [push]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
      - name: Execute Gradle build
        run: ./gradlew build
  lint-markdown:
    name: Lint all markdowns in project
    runs-on: ubuntu-latest
    steps:
      - name: Lintmark downs
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .